version: 2

sources:
  - name: summary_your_dataset    
    database: peppy-primacy-455413-d8      
    schema: summary_your_dataset      
    tables:
      - name: change_data_type  
      - name: product_name_crawl
      - name: ip2_location

models:
# Schema for staging dimesion tables
  - name: stg_date
    description: "Staging view for user data"
  - name: stg_product
    description: "Staging view for product data"
  - name: stg_location
    description: "Staging view for location data"

#Schema for staging  fact tables
  - name: stg_change_data_type
    description: "Staging model for cleaned and transformed change_data_type data"
    columns:
      - name: order_id
        description: "Order ID"
        tests:
          - not_null
      - name: time_stamp
        description: "Timestamp of the event"
        tests:
          - not_null
      - name: local_time
        description: "Local datetime of the event"
      - name: user_id_db
        description: "User ID"
        tests:
          - not_null
      - name: device_id
        description: "Device ID"
      - name: ip
        description: "IP address"
      - name: user_agent
        description: "User agent string"
      - name: resolution
        description: "Screen resolution"
      - name: api_version
        description: "API version"
      - name: store_id
        description: "Store ID"
      - name: product_id
        description: "Product ID"
      - name: cat_id
        description: "Category ID"
      - name: collect_id
        description: "Collection ID"
      - name: viewing_product_id
        description: "Viewed product ID"
      - name: recommendation_product_id
        description: "Recommended product ID"
      - name: recommendation_clicked_position
        description: "Position of clicked recommendation"
      - name: price
        description: "Price of the event"
      - name: currency
        description: "Currency of the price"
      - name: is_paypal
        description: "Payment method indicator"
      - name: utm_source
        description: "UTM source"
      - name: utm_medium
        description: "UTM medium"
      - name: current_url
        description: "Current URL"
      - name: referrer_url
        description: "Referring URL"
      - name: key_search
        description: "Search keyword"
      - name: email_address
        description: "Email address"
      - name: show_recommendation
        description: "Show recommendation status"
      - name: recommendation
        description: "Recommendation type"
      - name: cart_products
        description: "Array of cart products"
        tests:
          - not_null
      - name: options
        description: "Array of product options"
      - name: collection
        description: "Collection type"
        tests:
          - not_null
    
#Schema for dimensions and facts
  - name: dim_product
    description: "Dimension table for product information"
    columns:
      - name: product_id
        description: "Unique identifier for the product"
        tests:
          - not_null
          - unique
          
  - name: dim_user
    description: "Dimension table for user information"
    columns:
      - name: user_id_db
        description: "Unique identifier for the user"
        tests:
          - not_null
          - unique 
      - name: email_address
        description: "Email address of the user"
        tests:
          - not_null
          - unique
  - name: dim_date
    description: "Dimension table for time information extracted"
    columns:
        - name: time_id
          description: "Unique identifier for each time entry"
          tests:
            - not_null
            - unique
        - name: year
          description: "Year extracted from timestamp"
          tests:
            - not_null
        - name: month
          description: "Month extracted from timestamp"
          tests:
            - not_null
        - name: day
          description: "Day extracted from timestamp"
          tests:
            - not_null
        - name: hour
          description: "Hour extracted from timestamp"
          tests:
            - not_null
        - name: minute
          description: "Minute extracted from timestamp"
          tests:
            - not_null
        - name: week_of_year
          description: "Week number of the year"
          tests:
            - not_null
        - name: quarter
          description: "Quarter of the year"
          tests:

            - not_null
        - name: day_of_week
          description: "Day of the week (e.g., Monday)"
          tests:
            - not_null
  
  - name: fact_checkout_success
    description: "Fact table for successful checkout events"
    columns:
        - name: fact_id
          description: "Unique identifier for the fact entry"
          tests:
            - not_null
            - unique
        - name: order_id
          description: "Order ID linked to dim_order"
          tests:
            - not_null
        - name: time_id
          description: "Time ID linked to dim_time"
          tests:
            - not_null
        - name: user_id_db
          description: "User ID linked to dim_user"
          tests:
            - not_null
        - name: product_id
          description: "Product ID linked to dim_product"
          tests:
            - not_null
        - name: store_id
          description: "Store ID linked to dim_store"
        - name: total_price
          description: "Total price of the checkout"
          tests:
            - not_null
        - name: quantity
          description: "Total quantity of products in the checkout"
          tests:
            - not_null
        - name: is_paypal
          description: "Payment method indicator"
        - name: cart_product_count
          description: "Number of products in the cart"
          tests:
            - not_null
  - name: dim_location
    description: "Dimension table for location information"
    columns:
        - name: ip
          description: "IP address"
          tests:
            - not_null
        - name: country
          description: "Country "
          tests:
            - not_null
        - name: region
          description: "Region"
          tests:
            - not_null
        - name: city
          description: "City"
          tests:
            - not_null
  
